import { STORAGE_KEY } from '@/constants/ui';

const SETTINGS_EXPORT_EXCLUDE = new Set<string>([
  STORAGE_KEY.TEAMS_BUILDER_DRAFT,
  STORAGE_KEY.TEAMS_BUILDER_SLOTS,
  STORAGE_KEY.TIER_LIST_BUILDER_DRAFT,
  STORAGE_KEY.TIER_LIST_BUILDER_SLOTS,
]);

export const SETTINGS_STORAGE_KEYS = Object.values(STORAGE_KEY).filter(
  (key) => !SETTINGS_EXPORT_EXCLUDE.has(key)
);
